#Altera o sshd_config e altera o usedns
- hosts: all
  sudo: yes
  gather_facts: False
  remote_user: root

  tasks: 
    - name: Verificar se o sshd_config existe
      stat: path=/etc/ssh/sshd_config
      register: sshd_config

    - name: Altero o sshd_config para nao usar o DNS
      lineinfile: dest=/etc/ssh/sshd_config regexp=^UseDNS= line=UseDNS=no
      when: sshd_config.stat.exists
      notify: restart sshd

  handlers:
        - name: restart sshd
          service: name=sshd state=restarted